-- Create the table for storing business inquiries
create table public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  mobile text not null,
  email text,
  company text not null,
  inquiry_type text not null, -- 'partnership', 'product', 'solution', 'other'
  message text not null,
  status text default 'pending'::text -- 'pending', 'contacted', 'closed'
);

-- Enable Row Level Security (RLS)
alter table public.inquiries enable row level security;

-- Policy 1: Allow public (anonymous) users to INSERT data
-- This allows the contact form on the website to work without user login
create policy "Allow public inserts"
on public.inquiries
for insert
to anon
with check (true);

-- Policy 2: Allow authenticated users (admins) to VIEW data
-- This protects the data so random visitors cannot read the inquiries
create policy "Allow authenticated reads"
on public.inquiries
for select
to authenticated
using (true);

-- Optional: Comment on table
comment on table public.inquiries is 'Stores business inquiries from the official website contact form.';
